# Generated by Django 4.1.7 on 2023-03-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='sysinfomanage',
            name='Sys_abbreviation',
            field=models.CharField(max_length=64, unique=True, verbose_name='系统简称'),
        ),
    ]
