# Generated by Django 4.1.7 on 2023-03-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('MonitorCenter', '0002_monitorobject_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostsinfo',
            name='sys_id',
        ),
        migrations.AddField(
            model_name='hostsinfo',
            name='sysinfo_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='hostsinfo',
            name='sysinfo_object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
