# Generated by Django 4.1.7 on 2023-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0003_remove_hostsinfo_sys_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsinfo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
