# Generated by Django 4.1.7 on 2023-03-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0004_hostsinfo_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='metrics_sys',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='monitor_object_id',
        ),
        migrations.CreateModel(
            name='MetricsSysInfoManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.metrics')),
                ('sys_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.sysinfomanage')),
            ],
        ),
        migrations.CreateModel(
            name='MetricsMonitorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.metrics')),
                ('monitor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.monitorobject')),
            ],
        ),
        migrations.CreateModel(
            name='MetricsHostsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.hostsinfo')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.metrics')),
            ],
        ),
        migrations.AddField(
            model_name='metrics',
            name='hosts_info',
            field=models.ManyToManyField(through='MonitorCenter.MetricsHostsInfo', to='MonitorCenter.hostsinfo'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='monitor_objects',
            field=models.ManyToManyField(through='MonitorCenter.MetricsMonitorObject', to='MonitorCenter.monitorobject'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='sys_info_manages',
            field=models.ManyToManyField(through='MonitorCenter.MetricsSysInfoManage', to='MonitorCenter.sysinfomanage'),
        ),
    ]
