# Generated by Django 4.1.7 on 2023-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0005_remove_metrics_metrics_sys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
