# Generated by Django 4.1.7 on 2023-03-29 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0006_metrics_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostSysMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.hostsinfo', verbose_name='主机ID')),
                ('sys_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.sysinfomanage', verbose_name='系统ID')),
            ],
            options={
                'verbose_name': '主机与系统关联',
                'verbose_name_plural': '主机与系统关联',
                'db_table': 'hostsysmapping',
            },
        ),
    ]
