# Generated by Django 4.1.7 on 2023-03-29 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0007_hostsysmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostsinfo',
            name='sysinfo_content_type',
        ),
        migrations.RemoveField(
            model_name='hostsinfo',
            name='sysinfo_object_id',
        ),
        migrations.CreateModel(
            name='HostObjMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.hostsinfo', verbose_name='主机ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorCenter.monitorobject', verbose_name='对象ID')),
            ],
            options={
                'verbose_name': '主机-对象映射关系',
                'verbose_name_plural': '主机-对象映射关系',
                'db_table': 'host_obj_mapping',
            },
        ),
    ]
