# Generated by Django 4.1.7 on 2023-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorCenter', '0008_remove_hostsinfo_sysinfo_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsinfo',
            name='objects',
            field=models.ManyToManyField(related_name='hostinfo_objects', through='MonitorCenter.HostObjMapping', to='MonitorCenter.monitorobject'),
        ),
        migrations.AddField(
            model_name='hostsinfo',
            name='systems',
            field=models.ManyToManyField(related_name='hostinfo_systems', through='MonitorCenter.HostSysMapping', to='MonitorCenter.sysinfomanage'),
        ),
    ]
